image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup & Services
    init: |
      go mod download
      go install golang.org/x/tools/cmd/stringer@latest

    command: |
      # Longer git credential cache
      git config --global credential.helper 'cache --timeout=36000'

vscode:
  extensions:
    - golang.go

    - akosyakov.gitpod-monitor
    - mhutchie.git-graph
    - thinker.copy-as-snippet
